apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-app2
  namespace: webapps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache-app2
  template:
    metadata:
      labels:
        app: apache-app2
    spec:
      containers:
      - name: apache
        image: httpd:2.4-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: html
        configMap:
          name: apache-app2-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-app2-html
  namespace: webapps
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Apache App 2</title></head>
    <body style="background: #ecf0f1; font-family: Arial; padding: 40px;">
      <h1>🏢 Buurman en Buurman IT</h1>
      <h2>Apache Application 2</h2>
      <p>Second Apache webserver behind NGINX reverse proxy</p>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: apache-app2-service
  namespace: webapps
spec:
  selector:
    app: apache-app2
  ports:
  - port: 80
    targetPort: 80
