apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-app1
  namespace: webapps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache-app1
  template:
    metadata:
      labels:
        app: apache-app1
    spec:
      containers:
      - name: apache
        image: httpd:2.4-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: html
        configMap:
          name: apache-app1-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-app1-html
  namespace: webapps
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Apache App 1</title></head>
    <body style="background: #f0f0f0; font-family: Arial; padding: 40px;">
      <h1>🏢 Buurman en Buurman IT</h1>
      <h2>Apache Application 1</h2>
      <p>First Apache webserver behind NGINX reverse proxy</p>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: apache-app1-service
  namespace: webapps
spec:
  selector:
    app: apache-app1
  ports:
  - port: 80
    targetPort: 80
